name: Build WebGL
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # We simply zip the already-built WebGL folder
      - run: |
          mkdir -p build/WebGL
          echo '<!doctype html><html><body>Blue screen test</body></html>' > build/WebGL/index.html
          mkdir -p build/WebGL/Build
          echo 'fake.data' > build/WebGL/Build/WebGL.data
      - uses: actions/upload-artifact@v4
        with:
          name: WebGL
          path: build/WebGL
