name: Build WebGL
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: game-ci/unity-builder@v4
        with:
          targetPlatform: WebGL
          unityVersion: 2022.3.47f1
          customImage: 'unityci/editor:2022.3.47f1-webgl-1'  # personal license built-in
      - uses: actions/upload-artifact@v4
        with:
          name: WebGL
          path: build/WebGL
